insert into games (user_id, score) values (1, 200);
insert into games (user_id, score) values (1, 300);
insert into games (user_id, score) values (1, 20);
insert into games (user_id, score) values (1, 220);
insert into games (user_id, score) values (2, 120);
insert into games (user_id, score) values (2, 50);
insert into games (user_id, score) values (2, 40);
insert into games (user_id, score) values (3, 40);
insert into games (user_id, score) values (3, 120);
insert into games (user_id, score) values (3, 140);
insert into games (user_id, score) values (4, 140);
insert into games (user_id, score) values (4, 10);
insert into games (user_id, score) values (4, 100);
insert into games (user_id, score) values (4, 1000)
