// Generated by CoffeeScript 1.6.3
(function() {
  var a0, a1, a2, a3;

  a0 = [1, 2, 3, 5];

  a1 = [1, 5, 8, 2, 4, 2];

  a2 = {
    "sato": 100,
    "sasaki": 200
  };

  a3 = {
    "sato": {
      "sales": 200,
      "cost": 80
    },
    "sasaki": {
      "sales": 250,
      "cost": 40
    }
  };

}).call(this);
