// Generated by CoffeeScript 1.6.3
(function() {
  var a, i, index, _i, _j, _len;

  for (i = _i = 0; _i <= 3; i = ++_i) {
    alert(i);
  }

  a = ["tanaka", "taguchi", "sasaki"];

  for (index = _j = 0, _len = a.length; _j < _len; index = ++_j) {
    i = a[index];
    alert("hi, " + index + ":" + i);
  }

}).call(this);
