// Generated by CoffeeScript 1.6.3
(function() {
  var message, name, s;

  message = "hello world";

  if (message.length > 1) {
    alert(message);
  }

  s = "this is a pen.\nthis is a panda.\nthis is the end";

  name = "taguchi";

  alert("hi, " + name);

}).call(this);
