// Generated by CoffeeScript 1.6.3
(function() {
  var signal, x;

  signal = "red";

  if (signal === "red") {
    alert("stop!");
  } else if (signal === "green") {
    alert("go");
  } else {
    alert("coution!");
  }

  x = 20;

  if ((10 < x && x < 30)) {
    alert("true");
  }

}).call(this);
