// Generated by CoffeeScript 1.6.3
(function() {
  var signal;

  signal = "red";

  switch (signal) {
    case "red":
      alert("stop!");
      break;
    case "green":
      alert("go!");
      break;
    default:
      alert("caution");
  }

}).call(this);
