$(function(){var a={ccode:"",media_code:"1",region_code:"tokyo",pack_code:"",channel_genre_code:"",date:"",hour_start:"",hour_end:"",page:1}a=getParams(a,Array("media_code","region_code","pack_code","channel_genre_code"));
	var c=null,b=null,h=null,i=null,j=null,f=null,g=null,m=null,o=0,d="";
	setHandlerToPostThisSizeToParentWindow();
	v();
	function v(){$.ajax({url:BASE_URL+"api/medias",data:"callback=?&ccode="+urlencode(a.ccode),type:"GET",dataType:"jsonp",jsonp:"callback",cache:false,async:false,timeout:5e3,success:function(d){if(d.error==0){b=d.medias;
		c=d.client;
		if(b.length<=0){e("\u8a72\u5f53\u30af\u30e9\u30a4\u30a2\u30f3\u30c8\u306b\u3001\u5229\u7528\u53ef\u80fd\u306a\u30e1\u30c7\u30a3\u30a2\u304c\u8a2d\u5b9a\u3055\u308c\u3066\u3044\u307e\u305b\u3093");
			return}if(!empty(c.available_pack_code)){a.media_code=b[0].code;
				l()}else p()}else e("getMedias() failed("+d.error+")")},error:function(c,a){e("getMedias() "+a)}})}function p(){if(offsetFromCode(b,"code",a.media_code)==-1)a.media_code=getDefaultCode(b,"code");
		var c=offsetFromCode(b,"code",a.media_code);
		if(b[c].select_region==0){n();
			return}$.ajax({url:BASE_URL+"api/regions",data:"callback=?&ccode="+urlencode(a.ccode)+"&media_code="+urlencode(a.media_code),type:"GET",dataType:"jsonp",jsonp:"callback",cache:false,async:false,timeout:5e3,success:function(a){if(a.error==0){h=a.regions;
				n()}else e("getRegions() failed("+a.error+")")},error:function(c,a){e("getRegions() "+a)}})}function n(){var c=offsetFromCode(b,"code",a.media_code);
				if(b[c].select_region!=0)if(offsetFromCode(h,"code",a.region_code)==-1)a.region_code=getDefaultCode(h,"code");
				if(b[c].select_pack==0){l();
					return}$.ajax({url:BASE_URL+"api/packs",data:"callback=?&ccode="+urlencode(a.ccode)+"&media_code="+urlencode(a.media_code)+"&region_code="+urlencode(a.region_code),type:"GET",dataType:"jsonp",jsonp:"callback",cache:false,async:false,timeout:5e3,success:function(a){if(a.error==0){i=a.packs;
						l()}else e("getPacks() failed("+a.error+")")},error:function(c,a){e("getPacks() "+a)}})}function l(){var c=offsetFromCode(b,"code",a.media_code);
						if(b[c].select_channel_genre==0){k();
							return}$.ajax({url:BASE_URL+"api/channel_genres",data:"callback=?&ccode="+urlencode(a.ccode)+"&media_code="+urlencode(a.media_code),type:"GET",dataType:"jsonp",jsonp:"callback",cache:false,async:false,timeout:5e3,success:function(a){if(a.error==0){j=a.channel_genres;
								j.unshift({code:"",name:"\u30c1\u30e3\u30f3\u30cd\u30eb\u30b8\u30e3\u30f3\u30eb\u304b\u3089\u9078\u629e\u3059\u308b"});
								k()}else e("getChannel_genres() failed("+a.error+")")},error:function(c,a){e("getChannel_genres() "+a)}})}function k(){var f=offsetFromCode(b,"code",a.media_code);
								if(empty(c.available_pack_code))if(b[f].select_pack!=0)if(offsetFromCode(i,"code",a.pack_code)==-1)a.pack_code=getDefaultCode(i,"code");
								if(b[f].select_channel_genre!=0)if(offsetFromCode(j,"code",a.channel_genre_code)==-1)a.channel_genre_code="";
								q();
								var g=r();
								setCookies(a,Array("media_code","region_code","pack_code","channel_genre_code"));
								var d="callback=?&ccode="+urlencode(a.ccode)+"&pack_code="+urlencode(g);
								d+="&date="+a.date;
								d+="&hour_start="+a.hour_start;
								d+="&hour_end="+a.hour_end;
								d+="&channel_offset="+(a.page-1)*PAGE_CHANNELS;
								d+="&channel_limit="+PAGE_CHANNELS;
								var f=offsetFromCode(b,"code",a.media_code);
								if(b[f].select_channel_genre!=0)d+="&channel_genre_code="+a.channel_genre_code;
								$.ajax({url:BASE_URL+"api/epg",data:d,type:"GET",dataType:"jsonp",jsonp:"callback",cache:false,async:false,timeout:5e3,success:function(a){if(a.error==0){o=a.total_channels;
									m=a.channels;
									if(!empty(c.available_pack_code))i=a.pack;
									s();
									u();
									t();
									"ajax"in c&&postThisSizeToParentWindow("dummy")}else e("getPrograms() failed("+a.error+")")},error:function(c,a){e("getPrograms() "+a)}})}function q(){var h=getNowDateObject(),c=h.getHours(),i=hhmmFromObject(h,2),f=timeFromHhmm(i),d=i.substring(0,8);
									if(empty(a.date))a.date=d;
									var g=timeFromHhmm(a.date+"0000");
									if(c<5){c+=24;
										f-=24*60;
										d=hhmmFromObject(objectFromTime(f),2).substring(0,8);
										if(empty(a.hour_start)){g-=24*60;
											a.date=hhmmFromObject(objectFromTime(g),2).substring(0,8)}}if(g<f)a.date=d;
											var e=BEG_TIMES.length,b;
											if(empty(a.hour_start))for(b=0;
													b<e-1;
													b++)if(c>=BEG_TIMES[b]&&c<END_TIMES[b]){a.hour_start=BEG_TIMES[b];
												a.hour_end=END_TIMES[b];
												break}a.hour_start=parseInt(a.hour_start);
												if(a.hour_start<5)a.hour_start+=24;
												if(a.hour_start>=29)a.hour_start=28;
												if(empty(a.hour_end)){for(b=0;
														b<e;
														b++)if(a.hour_start==BEG_TIMES[b]){a.hour_end=END_TIMES[b];
													break}if(b>=e)a.hour_end=a.hour_start+7}a.hour_end=parseInt(a.hour_end);
													if(a.hour_end<=a.hour_start)a.hour_end=a.hour_start+7;
													if(a.hour_end>29)a.hour_end=29;
													if(a.date==d)if(a.hour_end<=c)for(b=0;
															b<e;
															b++)if(END_TIMES[b]>c){a.hour_start=BEG_TIMES[b];
														a.hour_end=END_TIMES[b];
														break}}function r(){if(!empty(c.available_pack_code))return c.available_pack_code;
															var d=offsetFromCode(b,"code",a.media_code);
															if(b[d].select_pack!=0)return a.pack_code;
															else if(b[d].select_region!=0){var e=offsetFromCode(h,"code",a.region_code);
																return h[e].pack_code}return b[d].pack_code}function s(){var k=getNowDateObject(),n=k.getHours(),q=hhmmFromObject(k,2),r=timeFromHhmm(q),p=q.substring(0,8);
																	if(n<5){n+=24;
																		r-=24*60;
																		k=objectFromTime(r);
																		p=hhmmFromObject(k,2).substring(0,8)}var e;
																		f=[];
																		for(e=0;
																				e<8;
																				e++){f[e]={};
																			f[e].code=hhmmFromObject(k,2).substring(0,8);
																			var u=1+k.getMonth();
																			f[e].name=u+"/"+k.getDate()+"\uff08"+WEEKS[k.getDay()]+"\uff09";
																			var t=k.getTime()+24*60*60*1e3;
																			k.setTime(t)}g=[];
																			for(e=0;
																					e<5;
																					e++){g[e]={};
																				g[e].code=e;
																				if(e==4)g[e].name="24\u6642\u9593\u8868\u793a";
																				else{var l=BEG_TIMES[e]>=24?BEG_TIMES[e]-24:BEG_TIMES[e],s=END_TIMES[e]>=24?END_TIMES[e]-24:END_TIMES[e];
																					g[e].name=l+":00 - "+s+":00"}g[e].can_select=1;
																					if(a.date==p)if(END_TIMES[e]<=n)g[e].can_select=0}var o=offsetFromCode(b,"code",a.media_code),m;
																					d="";
																					for(e=0;
																							e<f.length;
																							e++)if(a.date==f[e].code.substring(0,8)){d=f[e].name;
																						d=d.replace("/","\u6708");
																						d=d.replace("\uff08","\u65e5\uff08");
																						break}var l=a.hour_start;
																						if(a.date==p)if(l<n)l=n;
																						d+=" "+(l>=24?l-24:l);
																						d+="-"+(a.hour_end>=24?a.hour_end-24:a.hour_end);
																						d+="\u6642";
																						if(!empty(c.available_pack_code))d+=" \u3014"+i.name+"\u3015";
																						else{d+=" \u3014"+b[o].name+"\u3015";
																							if(b[o].select_region!=0){m=offsetFromCode(h,"code",a.region_code);
																								d+="\uff0d \u3014"+h[m].name+"\u3015"}if(b[o].select_pack!=0){m=offsetFromCode(i,"code",a.pack_code);
																									d+="\uff0d \u3014"+i[m].name+"\u3015"}}if(b[o].select_channel_genre!=0){m=offsetFromCode(j,"code",a.channel_genre_code);
																										d+="\uff0d \u3014"+j[m].name+"\u3015"}}function u(){var l=offsetFromCode(b,"code",a.media_code),e;
																											$("#tvg_content #now_program").html(htmlspecialchars(d));
																											if(!empty(c.available_pack_code)){$("#tvg_content #media").hide();
																												$("#tvg_content #region").hide();
																												$("#tvg_content #pack").hide()}else{e="";
																													$.each(b,function(){e+='<option value="'+this.code+'"';
																														if(this.code==a.media_code)e+=" selected";
																														e+=">"+this.name+"</option>"});
																													$("#tvg_content #media").html(e).show();
																													if(b[l].select_region==0)$("#tvg_content #region").hide();
																													else{e="";
																														$.each(h,function(){e+='<option value="'+this.code+'"';
																															if(this.code==a.region_code)e+=" selected";
																															e+=">"+this.name+"</option>"});
																														$("#tvg_content #region").html(e).show()}if(b[l].select_pack==0)$("#tvg_content #pack").hide();
																														else{e="";
																															$.each(i,function(){e+='<option value="'+this.code+'"';
																																if(this.code==a.pack_code)e+=" selected";
																																e+=">"+this.name+"</option>"});
																															$("#tvg_content #pack").html(e).show()}}if(b[l].select_channel_genre==0)$("#tvg_content #channel_genre").hide();
																											else{e='<select id="channel_genre">';
																												$.each(j,function(){e+='<option value="'+this.code+'"';
																													if(this.code==a.channel_genre_code)e+=" selected";
																													e+=">"+this.name+"</option>"});
																												e+="";
																												$("#tvg_content #channel_genre_p").html(e).show()}$.each(f,function(b){if(this.code!=a.date){e='<a id="dates'+b+'" href="">'+this.name+"</a>";
																													$("#tvg_content #date"+b).removeClass("date, date_active").addClass("date")}else{e=this.name;
																														$("#tvg_content #date"+b).removeClass("date, date_active").addClass("date_active")}$("#tvg_content #date"+b).html(e)});
																												$.each(g,function(b){if(this.can_select==1&&(BEG_TIMES[this.code]!=a.hour_start||END_TIMES[this.code]!=a.hour_end)){e='<a id="times'+b+'" href="">'+this.name+"</a>";
																													$("#tvg_content #time"+b).removeClass("time, time_active").addClass("time")}else{e=this.name;
																														$("#tvg_content #time"+b).removeClass("time, time_active").addClass("time_active")}$("#tvg_content #time"+b).html(e)});
																												e="";
																												if(a.page>1)e+='<a id="pages1_prev" href="">\u524d\u306e\u30c1\u30e3\u30f3\u30cd\u30eb</a>';
																												else e+="\u524d\u306e\u30c1\u30e3\u30f3\u30cd\u30eb";
																												e+="\u3000|\u3000";
																												if(a.page<Math.ceil(o/PAGE_CHANNELS))e+='<a id="pages1_next" href="">\u6b21\u306e\u30c1\u30e3\u30f3\u30cd\u30eb</a>';
																												else e+="\u6b21\u306e\u30c1\u30e3\u30f3\u30cd\u30eb";
																												$("#tvg_content #page1").html(e);
																												$("#tvg_content #dates0, #dates1, #dates2, #dates3, #dates4, #dates5, #dates6, #dates7").click(function(e){var d=this.id,b=d.substring(5);
																													a.date=f[b].code;
																													if("ajax"in c)k();
																													else reloadParentWindow(PARENT_URL,stringFromParams(a));
																													e.preventDefault()});
																												$("#tvg_content #times0, #times1, #times2, #times3, #times4").click(function(e){var d=this.id,b=d.substring(5);
																													a.hour_start=BEG_TIMES[g[b].code];
																													a.hour_end=END_TIMES[g[b].code];
																													if("ajax"in c)k();
																													else reloadParentWindow(PARENT_URL,stringFromParams(a));
																													e.preventDefault()});
																												$("#tvg_content #pages1_prev, #pages1_next").click(function(e){var d=this.id,b=d.substring(7);
																													if(b=="prev")--a.page;
																													else if(b=="next")++a.page;
																													if("ajax"in c)k();
																													else reloadParentWindow(PARENT_URL,stringFromParams(a));
																													e.preventDefault()})}$("#tvg_content #media").change(function(){a.media_code=$(this).val();
																													a.pack_code="";
																													a.page=1;
																													if("ajax"in c)p();
																													else reloadParentWindow(PARENT_URL,stringFromParams(a))});
																													$("#tvg_content #region").change(function(){a.region_code=$(this).val();
																														a.pack_code="";
																														a.page=1;
																														if("ajax"in c)n();
																														else reloadParentWindow(PARENT_URL,stringFromParams(a))});
																													$("#tvg_content #pack").change(function(){a.pack_code=$(this).val();
																														a.page=1;
																														if("ajax"in c)l();
																														else reloadParentWindow(PARENT_URL,stringFromParams(a))});
																													$("#tvg_content #channel_genre").change(function(){a.channel_genre_code=$(this).val();
																														a.page=1;
																														if("ajax"in c)k();
																														else reloadParentWindow(PARENT_URL,stringFromParams(a))});
																													function t(){var r,b='<table border="0" cellpadding="0" cellspacing="1" class="program" bgcolor="#cccccc">';
																														b+="<tr>";
																														b+='<th class="txt02">\u3000</th>';
																														r=0;
																														$.each(m,function(a){if(a++>=PAGE_CHANNELS)return;
																															b+='<td class="frame">';
																															b+='<div class="channel_handle">';
																															b+='<div class="c_name_1_1 txt01_none"></div>';
																															b+='<div class="c_name_1_2 txt01_none">';
																															if(this.station.url)b+='<a href="'+this.station.url+'" target="_blank">'+htmlspecialchars(this.station.name)+"</a>";
																															else b+='<span class="nolink">'+htmlspecialchars(this.station.name)+"</span>";
																															b+="</div>";
																															b+='<div class="c_name_1_3 txt02">'+htmlspecialchars(this.display_channel)+"</div>";
																															b+="</div>";
																															b+="</td>"});
																														b+="<td></td>";
																														b+="</tr>";
																														for(var q=getNowDateObject(),t=timeFromHhmm(hhmmFromObject(q,1)),s=timeFromHhmm(hhmmFromObject(q,2)),n=0;
																																n<8;
																																n++)if(a.date==f[n].code)break;
																														if(n>=8)n=0;
																														var d=s+n*24*60+a.hour_start*60,i=s+n*24*60+a.hour_end*60;
																														if(q.getHours()<5){d-=24*60;
																															i-=24*60}if(d<t)d=t;
																															var g=[0,0,0,0,0,0,0],o=[0,0,0,0,0,0,0],l=[d,d,d,d,d,d,d],e,j;
																															$.each(m,function(a){o[a]=this.programs.length;
																																for(g[a]=0;
																																	g[a]<o[a];
																																	g[a]++){e=timeFromHhmm(this.programs[g[a]].start,0);
																																	j=timeFromHhmm(this.programs[g[a]].end,0);
																																	if(e<d&&j>d||e>=d)break}for(;
																																		o[a]>g[a];
																																		o[a]--){e=timeFromHhmm(this.programs[o[a]-1].start,0);
																																		if(e<i)break}});
																															for(var u,k,p,h=d;
																																	h<i;
																																	h++){b+="<tr>";
																																if(h%60==0){u=objectFromTime(h);
																																	b+='<th rowspan="60" class="txt02">'+u.getHours()+"</th>"}r=0;
																																	$.each(m,function(a){if(r++>=PAGE_CHANNELS)return;
																																		if(g[a]<o[a]){e=timeFromHhmm(this.programs[g[a]].start,0);
																																			j=timeFromHhmm(this.programs[g[a]].end,0);
																																			k=0;
																																			if(h==d&&e<h&&j>h)if(j>i)k=i-d;
																																			else k=j-h;
																																			else if(e==h)if(j>i)k=i-e;
																																			else k=j-e;
																																			if(k>0){var f=this.programs[g[a]];
																																				++g[a];
																																				l[a]+=k;
																																				var m="",n="";
																																				$.each(MODE_KEYS,function(){if(this.key in f){var a=f[this.key];
																																					if(this.icon<0){if(a!=0&&a!=null){var d=Math.abs(this.icon),c=SP_MODE_ICONS[d][a];
																																						if(c!=0)m+='<img src="'+BASE_URL+"img/icon/"+c+'.gif" alt="'+this.name+'" width="15" height="15" />'}}else if(this.icon!=0)if(a!=0&&a!=null){var b='<img src="'+BASE_URL+"img/icon/"+this.icon+'.gif" alt="'+this.name+'" width="15" height="15" style="vertical-align:top;
																																							" />';
																																							if(this.last==0)m+=b;
																																							else n+=b}}});
																																				if(m!="")m='<div class="program_icon">'+m+"</div>";
																																				var q="";
																																				$.each(GENRE_CODES,function(){if(f.main_genre_code==this.code)q=" "+this.bg});
																																				b+='<td rowspan="'+k+'" valign="top" class="frame'+q+'">';
																																				b+='<table border="0" cellpadding="0" cellspacing="0" class="none txt01" width="134" style="table-layout:fixed;
																																				word-break:break-all;
																																				word-wrap:break-word;
																																				white-space:pre-wrap;
																																				overflow:auto;
																																					 "><tr><td>';
																																					 b+='<div class="program_text_1">'+hhmmFromHhmm(f.start)+"</div>";
																																					 b+=m;
																																					 var s=c.detail_url+"?station_code="+urlencode(this.station.code)+"&start="+urlencode(f.start);
																																					 b+='<div class="program_text_2" style="line-height:1.6em;
																																					 ">';
																																					 b+='<a href="'+s+'" target="_parent">'+htmlspecialchars(f.title+f.sub_title)+"</a></div>";
																																					 b+="</div>";
																																					 b+=n;
																																					 b+='<div class="program_text_3">'+f.details+"</div>";
																																					 b+="</td></tr></table>";
																																					 b+="</td>"}else if(l[a]<=h){p=e-l[a];
																																						 b+='<td rowspan="'+p+'" valign="top" class="frame">';
																																						 b+="</td>";
																																						 l[a]=e}}else if(l[a]<=h){p=i-l[a];
																																							 b+='<td rowspan="'+p+'" valign="top" class="frame">';
																																							 b+="</td>";
																																							 l[a]=i}});
																																							 b+="<td></td>";
																																							 b+="</tr>"}b+="<tr>";
																																							 b+='<td width="18">';
																																							 b+='<img src="'+BASE_URL+'img/common/spacer.gif" alt="" width="18" height="1" />';
																																							 b+="</td>";
																																							 for(var v=0;
																																									 v<PAGE_CHANNELS;
																																									 v++){b+='<td width="100%">';
																																								 b+='<img src="'+BASE_URL+'img/common/spacer.gif" alt="" width="134" height="1" />';
																																								 b+="</td>"}b+="<td></td>";
																																								 b+="</tr>";
																																								 b+="</table>";
																																								 $("#tvg_content #program").html(b)}function e(a){$("#tvg_content #program").html('<div align="center" style="padding:32px;
																																										 0px 32px;
																																										 0px;
																																										 ">'+a+"</div>")}})
